language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- cargo build --verbose
- cargo build --release --verbose
- cargo test --verbose
- cargo test --release --verbose
- cargo fmt -- --write-mode=diff
matrix:
  include:
    - os: linux
      rust: nightly
      script: cargo bench --features unstable
    - os: linux
      rust: nightly
      script: cargo build --features asm --release
  allow_failures:
    - rust: nightly
