language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      rust: nightly
      script: benches/bench
    - os: osx
      rust: nightly
      script: benches/bench
  allow_failures:
    - rust: nightly
