language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
- cargo build --verbose
- cargo build --release --verbose
- cargo test --verbose
- cargo test --release --verbose
matrix:
  include:
    - os: linux
      rust: nightly
      script: cargo bench --features unstable
    - os: osx
      rust: nightly
      script: cargo bench --features unstable
  allow_failures:
    - rust: nightly
