[package]
name = "rpc-perf"
version = "0.1.2"
authors = ["Brian Martin <bmartin@twitter.com>"]

license = "apache-2.0"

description = "RPC Performance Testing"

homepage = ""
repository = ""

readme = "README.md"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[dependencies]
getopts = "0.2.14"
histogram = "0.3.3"
log = "0.3.3"
time = "0.1.34"
regex = "0.1.41"
shuteye = "0.0.5"
simple_logger = "0.4.0"
toml = "0.1.23"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"
branch = "v0.2.x"

[dependencies.mpmc]
git = "https://github.com/brayniac/mpmc"

[dependencies.mio]
path = "./deps/mio/"

[dependencies.parser]
path = "./deps/parser/"

[dependencies.request]
path = "./deps/request/"

[dependencies.workload]
path = "./deps/workload/"
