[package]
name = "rpc-perf"
version = "1.0.0-nightly"
authors = ["Brian Martin <bmartin@twitter.com>"]

license = "apache-2.0"

description = "RPC Performance Testing"

homepage = ""
repository = ""

readme = "README.md"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[dependencies]
bytes = "0.3.0"
getopts = "0.2.14"
heatmap = "0.1.7"
histogram = "0.3.6"
log = "0.3.5"
mio = "0.5.0"
regex = "0.1.41"
shuteye = "0.1.1"
simple_logger = "0.4.0"
time = "0.1.34"
toml = "0.1.27"
waterfall = "0.1.4"

[dependencies.mpmc]
git = "https://github.com/brayniac/mpmc"

[dependencies.parser]
path = "./lib/parser/"

[dependencies.request]
path = "./lib/request/"

[dependencies.workload]
path = "./lib/workload/"
