[package]
name = "workload"
version = "0.1.3"
authors = ["Brian Martin <bmartin@twitter.com>"]

license = "apache-2.0"

description = "rpc-perf workload generation"

[dependencies]
log = "0.3.5"
time = "0.1.34"
rand = "0.3.13"
ratelimit = "0.2.0"
shuteye = "0.1.0"

[dependencies.mpmc]
git = "https://github.com/brayniac/mpmc"

[dependencies.request]
path = "../request/"
