[package]
name = "workload"
version = "0.1.2"
authors = ["Brian Martin <bmartin@twitter.com>"]

license = "apache-2.0"

description = "rpc-perf workload generation"

[dependencies]
log = "0.3.3"
time = "0.1.24"
rand = "0.3.11"
ratelimit = "0.1.8"
shuteye = "0.0.5"

[dependencies.mpmc]
git = "https://github.com/brayniac/mpmc"

[dependencies.request]
path = "../request/"
